# Generated by Django 4.0.6 on 2022-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_problem_topic_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='problems',
        ),
        migrations.AddField(
            model_name='problem',
            name='problems',
            field=models.ManyToManyField(to='functions.topic'),
        ),
    ]
