# Generated by Django 4.0.6 on 2022-07-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_remove_topic_problems_problem_problems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problems',
            new_name='topics',
        ),
    ]
