# Generated by Django 4.0.6 on 2022-07-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0006_body_internship_delete_problem_delete_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=255)),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.internship')),
            ],
        ),
    ]
