# Generated by Django 4.0.6 on 2022-07-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0007_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='reason',
        ),
    ]
