# Generated by Django 4.0.6 on 2022-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0008_remove_applicants_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
